export const tags = [
    { value: "flows", label: "flows" },
    { value: "graph matchings", label: "graph matchings" },
    { value: "graphs", label: "graphs" },
    { value: "greedy", label: "greedy" },
    { value: "binary search", label: "binary search" },
    { value: "dp", label: "dp" },
    { value: "geometry", label: "geometry" },
    { value: "brute force", label: "brute force" },
    { value: "data structures", label: "data structures" },
    { value: "implementation", label: "implementation" },
    { value: "sortings", label: "sortings" },
    { value: "constructive algorithms", label: "constructive algorithms" },
    { value: "two pointers", label: "two pointers" },
    { value: "dfs and similar", label: "dfs and similar" },
    { value: "hashing", label: "hashing" },
    { value: "bitmasks", label: "bitmasks" },
    { value: "meet-in-the-middle", label: "meet-in-the-middle" },
    { value: "combinatorics", label: "combinatorics" },
    { value: "math", label: "math" },
    { value: "dsu", label: "dsu" },
    { value: "divide and conquer", label: "divide and conquer" },
    { value: "strings", label: "strings" },
    { value: "interactive", label: "interactive" },
    { value: "number theory", label: "number theory" },
    { value: "shortest paths", label: "shortest paths" },
    { value: "trees", label: "trees" },
    { value: "probabilities", label: "probabilities" },
    { value: "string suffix structures", label: "string suffix structures" },
    { value: "fft", label: "fft" },
    { value: "matrices", label: "matrices" },
    { value: "2-sat", label: "2-sat" },
    { value: "ternary search", label: "ternary search" },
    { value: "games", label: "games" },
    { value: "chinese remainder theorem", label: "chinese remainder theorem" },
    { value: "dfs", label: "dfs" },
    { value: "Array", label: "Array" },
    { value: "trie", label: "trie" },
    { value: "linked list", label: "linked list" },
    { value: "sliding window", label: "sliding window" },
    { value: "stack", label: "stack" },
    { value: "queue", label: "queue" },
];